name: Build .deb package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-python python3-all build-essential lintian

      - name: Build .deb Package
        env:
          DEBEMAIL: "anilrajrimal@gmail.com"
          DEBFULLNAME: "Anil Raj Rimal"
          LC_ALL: C
        run: |
          debuild -b -us -uc
          cp ../wtfport_*.deb .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wtfport-deb
          path: wtfport_*.deb
