name: Build .deb package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g., v1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-python python3-all build-essential lintian

      - name: Update changelog version to match tag
        run: |
          TAG_VERSION=${{ github.event.inputs.tag || github.ref_name }}
          VERSION="${TAG_VERSION#v}"
          dch -v "${VERSION}-1" --distribution unstable -m "ci build"

      - name: Build .deb Package
        env:
          DEBEMAIL: "anilrajrimal@gmail.com"
          DEBFULLNAME: "Anil Raj Rimal"
          LC_ALL: C
        run: |
          debuild -b -us -uc
          cp ../wtfport_*.deb .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wtfport-deb
          path: wtfport_*.deb

      - name: Create Release and upload .deb
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: 'wtfport_*.deb'
          tag: ${{ github.event.inputs.tag || github.ref_name }}
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) ||
          (github.event_name == 'workflow_dispatch')
